### PR TITLE
A great number of improvements

### PR DESCRIPTION
**Pull request by ralfstrandell**
We have a version 1.12.0 of psGeo in testing, that
a) filters articles
b) filters 3d models
c) allows on-the-fly redefinition on length etc categories
d) has Swedish, Norwegian and UK topographic maps
e) has a user interface (new MoreFilter window) which is more responsive and mobile optimized
A small number of hidden bugs were also removed.

### CODE REVIEW

**Comment by jariarkko** [comment]
I have now loaded this on my computer and am testing. Running uni tests and reading code. Later will run it on my website.

**Comment by ralfstrandell** [comment]
Lots of bugfixes since this pull request. A new one is in order.

**Comment by jariarkko** [comment]
kartta.html and index.htlm do not seem to include all the necessary files: settings, location, tables

**Comment by jariarkko** [comment]
And i pulled testing, not looking at this PR.

**Comment by jariarkko** [comment]
Plus I'm changing my side code to work with the new files, new init function, etc.

**Comment by jariarkko** [comment]
But I have to pause now to do some day job work. May return later today or tomorrow eve. So far so good though! No major issues except for the practical file stuff.

**Pull request closed without merging**
